- hosts: localhost
  become: true
  tasks:
    - name: Install mosh
      apt: name=mosh

    - name: Install volta
      shell: curl https://get.volta.sh | bash && export PATH="$HOME/.volta:$PATH"
      tags:
        - node
